Repository lininnin/csc207-proj, pull requests merged in 2025-07, with the labels that each got.

#7 updates to gpt api files
  src/entity/FeedbackEntry.java
  src/interface_adapter/PromptBuilder.java
  src/interface_adapter/gpt/OpenAIAPIAdapter.java
  src/interface_adapter/gpt/PromptBuilder.java
  src/interface_adapter/persistence/FeedbackRepositoryImpl.java
  src/use_case/FeedbackRepository.java
  src/use_case/GPTService.java
  src/use_case/GenerateFeedbackUseCase.java
Labels: documentation, enhancement

#15 Implement Team Story: Create, Organize, and Track Daily Tasks
  .idea/.gitignore
  pom.xml
  src/main/java/app/Main.java
  src/main/java/app/main.java
  src/main/java/data_access/2.java
  src/main/java/data_access/InMemoryDailyLogRepository.java
  src/main/java/data_access/InMemoryTaskRepository.java
  src/main/java/entity/BeginAndDueDates.java
  src/main/java/entity/DailyLog.java
  src/main/java/entity/DailyTaskSummary.java
  src/main/java/entity/Goal.java
  src/main/java/entity/Info.java
  src/main/java/entity/Task.java
  src/main/java/entity/TaskAvailable.java
  src/main/java/interface_adapter/4.java
  src/main/java/interface_adapter/controller/AddTaskToTodayController.java
  src/main/java/interface_adapter/controller/CreateTaskController.java
  src/main/java/interface_adapter/controller/MarkTaskCompleteController.java
  src/main/java/interface_adapter/presenter/AddTaskToTodayPresenter.java
  src/main/java/interface_adapter/presenter/CreateTaskPresenter.java
  src/main/java/interface_adapter/presenter/MarkTaskCompletePresenter.java
  src/main/java/use_case/add_task_to_today/AddTaskToTodayInputData.java
  src/main/java/use_case/add_task_to_today/AddTaskToTodayOutputBoundary.java
  src/main/java/use_case/add_task_to_today/AddTaskToTodayOutputData.java
  src/main/java/use_case/add_task_to_today/AddTaskToTodayUseCase.java
  src/main/java/use_case/create_task/CreateTaskInputData.java
  src/main/java/use_case/create_task/CreateTaskOutputBoundary.java
  src/main/java/use_case/create_task/CreateTaskOutputData.java
  src/main/java/use_case/create_task/CreateTaskUseCase.java
  src/main/java/use_case/generate_charts/GenerateChartsUseCase.java
  src/main/java/use_case/mark_task_complete/MarkTaskCompleteInputData.java
  src/main/java/use_case/mark_task_complete/MarkTaskCompleteOutputBoundary.java
  src/main/java/use_case/mark_task_complete/MarkTaskCompleteOutputData.java
  src/main/java/use_case/mark_task_complete/MarkTaskCompleteUseCase.java
  src/main/java/use_case/repository/DailyLogRepository.java
  src/main/java/use_case/repository/TaskRepository.java
  src/main/java/use_case/view_analytics/ViewAnalyticsUseCase.java
  src/main/java/view/TaskView.java
  src/main/java/view/TaskViewModel.java
  src/main/java/view/TaskViewModelUpdateListener.java
Labels: documentation

#18 #3 GPT API implementation
  src/main/java/data_access/FeedbackRepositoryImpl.java
  src/main/java/entity/FeedbackEntry.java
  src/main/java/interface_adapter/gpt/PromptBuilder.java
  src/main/java/interface_adapter/persistence/FeedbackRepositoryImpl.java
  src/main/java/use_case/GenerateFeedbackUseCase.java
Labels: documentation, enhancement

#89 add key to git ignore
  .idea/.gitignore
Labels: documentation

#95 #8 API changes
  src/main/java/interface_adapter/gpt/BayesCorrelationPromptBuilder.java
  src/main/java/interface_adapter/gpt/GeneralAnalysisPromptBuilder.java
  src/main/java/interface_adapter/gpt/OpenAIAPIAdapter.java
  src/main/java/interface_adapter/gpt/RecommendationPromptBuilder.java
  src/main/java/use_case/Ina/AnalyzeWellnessVSCompletionUseCase.java
  src/main/java/use_case/Ina/GPTService.java
  src/main/java/use_case/Ina/GenerateFeedbackUseCase.java
  src/main/java/use_case/Ina/ourAlgorithm/CorrelationAnalyzer.java
  src/main/java/use_case/Ina/ourAlgorithm/CorrelationAnalyzerImpl.java
  src/main/java/use_case/Ina/ourAlgorithm/RegressionResult.java
  src/main/java/view/ina/FeedbackHistoryController.java
  src/main/java/view/ina/FeedbackHistoryDialog.java
Labels: documentation, enhancement, Ina
